name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run Selenium tests
        env:
          CHROMEWEBDRIVER: /usr/local/share/chrome_driver
          DRIVER_PATH: /usr/local/bin
        run: dotnet test --configuration Release
